@Host = http://localhost:5015

###
GET {{Host}}/api/businesses/0a489d76-f4a4-44be-98ec-ac24ef51cb8a

###
GET {{Host}}/api/jobs


###
POST {{Host}}/api/auth/signup
Content-Type: application/json

{
  "email": "jobseeker1@example.com",
  "password": "password",
  "role": "JobSeeker",
  "name": "John Doe"
}

###

POST {{Host}}/api/auth/signin
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "test1234"
}

###




###
