// <auto-generated />
using System;
using System.Collections.Generic;
using JobBoard;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobBoard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobBoard.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bebc09a-e88c-4d5f-9a80-7e057f65a79d"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("faad2ee8-982f-4ea8-8840-4ece92faac94"),
                            Name = "JobSeeker",
                            NormalizedName = "JOBSEEKER"
                        },
                        new
                        {
                            Id = new Guid("02c7242b-4cb4-4467-a347-6094510ae46a"),
                            Name = "Business",
                            NormalizedName = "BUSINESS"
                        });
                });

            modelBuilder.Entity("JobBoard.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("JobBoard.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BusinessSizeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessSizeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("JobBoard.BusinessSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("BusinessSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1-10"
                        },
                        new
                        {
                            Id = 2,
                            Name = "11-50"
                        },
                        new
                        {
                            Id = 3,
                            Name = "51-200"
                        },
                        new
                        {
                            Id = 4,
                            Name = "201-500"
                        },
                        new
                        {
                            Id = 5,
                            Name = "501-1000"
                        },
                        new
                        {
                            Id = 6,
                            Name = "1001-5000"
                        },
                        new
                        {
                            Id = 7,
                            Name = "5001-10000"
                        },
                        new
                        {
                            Id = 8,
                            Name = "10001+"
                        });
                });

            modelBuilder.Entity("JobBoard.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engineering",
                            Slug = "engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "R&D",
                            Slug = "research-and-development"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Q&A",
                            Slug = "quality-assurance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sales",
                            Slug = "sales"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Marketing",
                            Slug = "marketing"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Human Resources",
                            Slug = "human-resources"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Information Technology",
                            Slug = "information-technology"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Finance",
                            Slug = "finance"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Customer Support",
                            Slug = "customer-support"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Product Management",
                            Slug = "product-management"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Legal",
                            Slug = "legal"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Technician",
                            Slug = "technicians"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Operations",
                            Slug = "operations"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Other",
                            Slug = "other"
                        });
                });

            modelBuilder.Entity("JobBoard.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AP",
                            Name = "Asia/Pacific Region"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 15,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 16,
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BQ",
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 29,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 31,
                            Code = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 32,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 33,
                            Code = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 34,
                            Code = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 35,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 36,
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 37,
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 38,
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 42,
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 44,
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 48,
                            Code = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 49,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 50,
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 51,
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 52,
                            Code = "CD",
                            Name = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            Id = 53,
                            Code = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 54,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 55,
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 56,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 57,
                            Code = "CW",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 58,
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 59,
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 60,
                            Code = "CI",
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 61,
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 62,
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 63,
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 64,
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 65,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 66,
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 67,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 68,
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 69,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 70,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 71,
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 72,
                            Code = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = 73,
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 74,
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 75,
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 76,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 77,
                            Code = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 78,
                            Code = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 79,
                            Code = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = 80,
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 81,
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 82,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 83,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 84,
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 85,
                            Code = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 86,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 87,
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 88,
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 89,
                            Code = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 90,
                            Code = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 91,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 92,
                            Code = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 93,
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 94,
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 95,
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 96,
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 97,
                            Code = "HM",
                            Name = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            Id = 98,
                            Code = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = 99,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 100,
                            Code = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 101,
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 102,
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 103,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 104,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 105,
                            Code = "IR",
                            Name = "Iran, Islamic Republic Of"
                        },
                        new
                        {
                            Id = 106,
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 107,
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 108,
                            Code = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 109,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 110,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 111,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 112,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 113,
                            Code = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 114,
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 115,
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 116,
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 117,
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 118,
                            Code = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            Id = 119,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 120,
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 121,
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 122,
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 123,
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 124,
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 125,
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 126,
                            Code = "LY",
                            Name = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            Id = 127,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 128,
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 129,
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 130,
                            Code = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = 131,
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 132,
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 133,
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 134,
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 135,
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 136,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 137,
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 138,
                            Code = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 139,
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 140,
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 141,
                            Code = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 142,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 143,
                            Code = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            Id = 144,
                            Code = "MD",
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            Id = 145,
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 146,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 147,
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 148,
                            Code = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 149,
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 150,
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 151,
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 152,
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 153,
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 154,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 155,
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 156,
                            Code = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = 157,
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 158,
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 159,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 160,
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 161,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 162,
                            Code = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 163,
                            Code = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 164,
                            Code = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 165,
                            Code = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 166,
                            Code = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 167,
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 168,
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 169,
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 170,
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 171,
                            Code = "PS",
                            Name = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            Id = 172,
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 173,
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 174,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 175,
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 176,
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 177,
                            Code = "PN",
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = 178,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 179,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 180,
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 181,
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 182,
                            Code = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = 183,
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 184,
                            Code = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 185,
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 186,
                            Code = "BL",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 187,
                            Code = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = 188,
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 189,
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 190,
                            Code = "MF",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = 191,
                            Code = "MF",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = 192,
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 193,
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 194,
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 195,
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 196,
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 197,
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 198,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 199,
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 200,
                            Code = "CS",
                            Name = "Serbia and Montenegro"
                        },
                        new
                        {
                            Id = 201,
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 202,
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 203,
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 204,
                            Code = "SX",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = 205,
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 206,
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 207,
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 208,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 209,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 210,
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 211,
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 212,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 213,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 214,
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 215,
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 216,
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 217,
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 218,
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 219,
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 220,
                            Code = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = 221,
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 222,
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 223,
                            Code = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = 224,
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 225,
                            Code = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 226,
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 227,
                            Code = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 228,
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 229,
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 230,
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 231,
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 232,
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 233,
                            Code = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 234,
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 235,
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 236,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 237,
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 238,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 239,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 240,
                            Code = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 241,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 242,
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 243,
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 244,
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 245,
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 246,
                            Code = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            Id = 247,
                            Code = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            Id = 248,
                            Code = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 249,
                            Code = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 250,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 251,
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 252,
                            Code = "ZW",
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            Id = 253,
                            Code = "AX",
                            Name = "Åland Islands"
                        });
                });

            modelBuilder.Entity("JobBoard.EmploymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Full Time"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Part Time"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Contract"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Internship"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Temporary"
                        });
                });

            modelBuilder.Entity("JobBoard.JobPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplyUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CompanyLogoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int>("EmploymentTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxSalary")
                        .HasColumnType("integer");

                    b.Property<int?>("MinSalary")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CountryId");

                    b.HasIndex("EmploymentTypeId");

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("JobBoard.JobPostPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckoutSessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId")
                        .IsUnique();

                    b.ToTable("JobPostPayments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JobBoard.Business", b =>
                {
                    b.HasOne("JobBoard.BusinessSize", "BusinessSize")
                        .WithMany()
                        .HasForeignKey("BusinessSizeId");

                    b.HasOne("JobBoard.ApplicationUser", "User")
                        .WithOne("Business")
                        .HasForeignKey("JobBoard.Business", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessSize");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobBoard.JobPost", b =>
                {
                    b.HasOne("JobBoard.Business", "Business")
                        .WithMany("JobPosts")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JobBoard.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBoard.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBoard.EmploymentType", "EmploymentType")
                        .WithMany()
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Category");

                    b.Navigation("Country");

                    b.Navigation("EmploymentType");
                });

            modelBuilder.Entity("JobBoard.JobPostPayment", b =>
                {
                    b.HasOne("JobBoard.JobPost", "JobPost")
                        .WithOne("Payment")
                        .HasForeignKey("JobBoard.JobPostPayment", "JobPostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("JobBoard.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("JobBoard.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("JobBoard.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("JobBoard.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBoard.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("JobBoard.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobBoard.ApplicationUser", b =>
                {
                    b.Navigation("Business");
                });

            modelBuilder.Entity("JobBoard.Business", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("JobBoard.JobPost", b =>
                {
                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
